version: '2'
services:
  php:
    build: .
    environment:
      XDEBUG_CONFIG: ${XDEBUG_CONFIG}
      PHP_IDE_CONFIG: ${PHP_IDE_CONFIG}
    volumes:
      - ../:/srv
    ports:
      - 8080:8080
      - 8081:8081
      - 14265:14265
    working_dir: /srv